<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use App\Models\PasswordPetugasKeuangan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PasswordPetugasKeuanganController extends Controller
{
    private function resolveRedirectTarget(Request $request, ?string $redirectUrl): string
    {
        $fallback = route('pendaftaran.statistik.keuangan');
        $target = trim((string) $redirectUrl);

        if ($target === '') {
            return $fallback;
        }

        if (str_starts_with($target, '//')) {
            return $fallback;
        }

        // Allow same-host relative paths (e.g. "/pendaftaran/statistik-keuangan")
        if (str_starts_with($target, '/')) {
            return $target;
        }

        // Allow same-host absolute URLs (e.g. generated by route())
        $parts = parse_url($target);

        if ($parts === false || empty($parts['host'])) {
            return $fallback;
        }

        $allowedHosts = array_filter([
            $request->getHost(),
            parse_url((string) config('app.url'), PHP_URL_HOST),
        ]);

        $hostOk = false;
        foreach ($allowedHosts as $allowedHost) {
            if (is_string($allowedHost) && $allowedHost !== '' && strcasecmp((string) $parts['host'], $allowedHost) === 0) {
                $hostOk = true;
                break;
            }
        }

        if (!$hostOk) {
            return $fallback;
        }

        $path = (string) ($parts['path'] ?? '/');

        if ($path === '' || !str_starts_with($path, '/')) {
            $path = '/';
        }

        if (!empty($parts['query'])) {
            $path .= '?' . $parts['query'];
        }

        if (!empty($parts['fragment'])) {
            $path .= '#' . $parts['fragment'];
        }

        return $path;
    }

    public function verifikasi(Request $request)
    {
        $request->validate([
            'nama' => 'required|string|max:100',
            'password' => 'required|string|max:50',
            'redirect_url' => 'nullable|string|max:500',
        ]);

        $nama = trim((string) $request->nama);
        $tujuan = $this->resolveRedirectTarget($request, $request->redirect_url);

        logAktivitas(
            'Petugas Keuangan Public - Submit Verifikasi Password',
            'Mengirim verifikasi password petugas keuangan atas nama ' . $nama . ' untuk akses halaman: ' . $tujuan . '.'
        );

        $data = PasswordPetugasKeuangan::where('nama', $nama)->first();

        if (!$data || !Hash::check($request->password, $data->password)) {
            logAktivitas(
                'Petugas Keuangan Public - Verifikasi Password Gagal',
                'Verifikasi gagal untuk nama petugas: ' . $nama . ' pada halaman: ' . $tujuan . '.'
            );

            return back()->with('error', 'Nama petugas atau password salah.');
        }

        session([
            'akses_keuangan_public' => true,
            'nama_petugas_keuangan_public' => $data->nama,
        ]);

        logAktivitas(
            'Petugas Keuangan Public - Verifikasi Password Berhasil',
            'Berhasil verifikasi petugas keuangan ' . $data->nama . '. Akses statistik keuangan dibuka untuk: ' . $tujuan . '.'
        );

        return redirect($tujuan);
    }
}
