<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\PasswordPanitia;
use Illuminate\Support\Facades\Hash;

class PasswordPanitiaController extends Controller
{
    private function resolveRedirectTarget(Request $request, ?string $redirectUrl): string
    {
        $fallback = route('pendaftaran.list');
        $target = trim((string) $redirectUrl);

        if ($target === '') {
            return $fallback;
        }

        if (str_starts_with($target, '//')) {
            return $fallback;
        }

        // Allow same-host relative paths (e.g. "/pendaftaran/123")
        if (str_starts_with($target, '/')) {
            return $target;
        }

        // Allow same-host absolute URLs (e.g. generated by route())
        $parts = parse_url($target);

        if ($parts === false || empty($parts['host'])) {
            return $fallback;
        }

        $allowedHosts = array_filter([
            $request->getHost(),
            parse_url((string) config('app.url'), PHP_URL_HOST),
        ]);

        $hostOk = false;
        foreach ($allowedHosts as $allowedHost) {
            if (is_string($allowedHost) && $allowedHost !== '' && strcasecmp((string) $parts['host'], $allowedHost) === 0) {
                $hostOk = true;
                break;
            }
        }

        if (!$hostOk) {
            return $fallback;
        }

        $path = (string) ($parts['path'] ?? '/');

        if ($path === '' || !str_starts_with($path, '/')) {
            $path = '/';
        }

        if (!empty($parts['query'])) {
            $path .= '?' . $parts['query'];
        }

        if (!empty($parts['fragment'])) {
            $path .= '#' . $parts['fragment'];
        }

        return $path;
    }

    public function verifikasi(Request $request)
    {
        $request->validate([
            'password' => 'required',
            'redirect_url' => 'nullable|string|max:500',
        ]);

        $tujuan = $this->resolveRedirectTarget($request, $request->redirect_url);
        $isJson = $request->expectsJson();
        
        logAktivitas(
            'Panitia Public - Submit Verifikasi Password',
            'Mengirim verifikasi password panitia untuk akses halaman: ' . $tujuan . '.'
        );

        $records = PasswordPanitia::orderByDesc('id')->get();

        if ($records->isEmpty()) {
            logAktivitas(
                'Panitia Public - Verifikasi Password Gagal',
                'Gagal verifikasi password karena data password panitia belum tersedia.'
            );
            
            if ($isJson) {
                return response()->json([
                    'error' => 'Password panitia belum dibuat'
                ], 400);
            }
            
            return back()->with('error','Password panitia belum dibuat');
        }

        $matched = null;
        foreach ($records as $data) {
            if (Hash::check($request->password, $data->password)) {
                $matched = $data;
                break;
            }
        }

        if (!$matched) {
            logAktivitas(
                'Panitia Public - Verifikasi Password Gagal',
                'Password panitia tidak sesuai saat mengakses: ' . $tujuan . '.'
            );
            
            if ($isJson) {
                return response()->json([
                    'error' => 'Password salah'
                ], 401);
            }
            
            return back()->with('error','Password salah');
        }

        session(['akses_pembayaran' => true]);

        logAktivitas(
            'Panitia Public - Verifikasi Password Berhasil',
            'Berhasil verifikasi password panitia (ID: ' . $matched->id . ', nama: ' . $matched->nama . '). Akses pembayaran dibuka untuk tujuan: ' . $tujuan . '.'
        );

        if ($isJson) {
            return response()->json([
                'success' => true,
                'message' => 'Password verified',
                'redirect' => $tujuan
            ]);
        }

        return redirect($tujuan);
    }
}
